# Generated by Django 4.2.1 on 2023-05-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
